#! /bin/bash

gcc -Wall -Werror -Wextra -pedantic -std=c99 -fPIC -g -c priority_queue.c

gcc -shared -o graph.so helpers.o graph.o

gcc -shared -o heap.so graph.o helpers.o heap.o

gcc -shared -o priority_queue.so heap.o graph.o helpers.o priority_queue.o

python2.7 -m unittest -v tests.test_priority_queue
